version: 2
jobs:
  test:
    environment:
      - GO111MODULE: "on"
      - CGO_ENABLED: "0"
    working_directory: /go/src/work
    docker:
      - image: makki0205/deploy
    steps:
      - checkout
      - run:
          name: yml file copy
          command: make create
      - run:
          name: go build
          command: make -f .circleci/ci.mk go/build
      - save_cache:
          key: build-{{ epoch }}
          paths:
            - .
  production:
    working_directory: /go/src/work
    docker:
      - image: makki0205/deploy
    steps:
      - setup_remote_docker:
          reusable: true
      - restore_cache:
          keys:
            - build
      - run:
          name: docker build
          command: make -f .circleci/ci.mk docker/build
      - run:
          name: aws login
          command: make -f .circleci/ci.mk login
      - run:
          name: docker push
          command: make -f .circleci/ci.mk docker/push
      - run:
          name: deploy
          command: make -f .circleci/ci.mk docker/deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - production:
          requires:
            - test
          filters:
            branches:
              only: master